version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database-1
      MYSQL_USER: admin
      MYSQL_PASSWORD: Ujwal9494
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s

  flask-backend:
    build: ./app-layer
    container_name: flask-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql-db
      DB_USER: admin
      DB_PASSWORD: Ujwal9494
      DB_NAME: database-1
    depends_on:
      mysql-db:
        condition: service_healthy
    volumes:
      - ./app-layer:/app

  nginx-frontend:
    build: ./static
    container_name: nginx-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - flask-backend
    volumes:
      - ./static:/usr/share/nginx/html

volumes:
  mysql_data:
