version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: flask-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./static
      dockerfile: Dockerfile.static
    container_name: nginx-frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
